misc_functions fixes and add cdr = cd [git] root

diff --git a/.bash/misc_functions b/.bash/misc_functions
--- a/.bash/misc_functions
+++ b/.bash/misc_functions
@@ -1,73 +1,66 @@
 #! /bin/bash
 
 declare -f mstat
-if [ "$(uname)" = "Linux" ]; then
+if [[ "$(uname)" = "Linux" ]]; then
     mstat() { stat -c %Y "$1"; }
 else
     mstat() { perl -e "print ((stat('$1'))[9])"; }
 fi
 
-gvim()
-{
+gvim() {
     local remote
     local servername
-    if [ -n "$TMUX" ]; then
-        servername=$(tmux -L outer list-windows -F '#{window_active} #{window_name}' 2>/dev/null | awk ' $1 == 1 { printf "%s", $2 } ')
-        command gvim --servername ${servername:-tmux} --remote "$@" 2>/dev/null
+    if [[ -n ${TMUX} ]]; then
+        servername=$(tmux -L outer list-windows -F '#{window_active} #{window_name}' 2> /dev/null | awk ' $1 == 1 { printf "%s", $2 } ')
+        command gvim --servername ${servername:-tmux} --remote "$@" 2> /dev/null
     else
-        if [ -n "$(command gvim --serverlist)" ]; then
+        if [[ -n $(command gvim --serverlist) ]]; then
             remote=--remote
         fi
-        command gvim $remote "$@" 2>/dev/null
+        command gvim "${remote}" "$@" 2> /dev/null
     fi
 }
 
-function every { 
+function every {
     awk "BEGIN{every=0;} {if ((every++ % $1) == 0) {print}}"
 }
 
-
-ln2cp()
-{
-# remove symbolic linked files and replace with a copy
-    for file in "$@"
-    do
-	if [[ -h $file ]]; then
-	    echo $file is symbolic link, replacing with a copy
-	    cp $file $file.$$ &&
-		rm -f $file &&
-		mv $file.$$ $file
-	else
-	    echo $file is not a symbolic link, ignoring
-	fi
+ln2cp() {
+    # remove symbolic linked files and replace with a copy
+    for file in "$@"; do
+        if [[ -L ${file} ]]; then
+            echo ${file} is symbolic link, replacing with a copy
+            cp ${file} ${file}.$$ \
+                && rm -f ${file} \
+                && mv ${file}.$$ ${file}
+        else
+            echo ${file} is not a symbolic link, ignoring
+        fi
     done
 }
 
-bashrc()
-{
+bashrc() {
     if [[ -z $1 ]]; then
-	vim ~/.bashrc
+        vim ~/.bashrc
     elif [[ -f ~/.bash/$1 ]]; then
-	vim ~/.bash/$1
+        vim ~/.bash/$1
     else
-	echo "bashrc: what did you mean by '$1'?" >&2
+        echo "bashrc: what did you mean by '$1'?" >&2
     fi
-    exec $SHELL
+    exec ${SHELL}
 }
-
 
 bgrm() {
     (
-    set -e
-    local dir
-    for dir in "$@"
-    do
-        cd "$dir"/..
-        TMPDIR=$(mktemp -d bgrm.XXXXXXXX)
-        mv "$dir" ${TMPDIR}
-        command rm -rf ${TMPDIR} &
-    done
-    wait
+        set -e
+        local dir
+        for dir in "$@"; do
+            cd "${dir}"/..
+            TMPDIR=$(mktemp -d bgrm.XXXXXXXX)
+            mv "${dir}" ${TMPDIR}
+            command rm -rf ${TMPDIR} &
+        done
+        wait
     ) &
 }
 
@@ -76,14 +69,26 @@ gitrmsubmodule() {
         echo "Run from top-level git directory please, .git directory not found"
         return 1
     }
-    for sm in "$@"
-    do
-        [[ -d .git/modules/$sm ]] || {
-            echo "Submodule $sm not found in .git/modules, skipping"
+    for sm in "$@"; do
+        [[ -d .git/modules/${sm} ]] || {
+            echo "Submodule ${sm} not found in .git/modules, skipping"
             continue
         }
-        rm -rf $sm
-        git gitrmsubmodule deinit -f -- $sm
-        rm -rf .git/modules/$sm
+        rm -rf ${sm}
+        git gitrmsubmodule deinit -f -- ${sm}
+        rm -rf .git/modules/${sm}
     done
 }
+
+cdr() {
+    local root rc
+
+    root=$(git rev-parse --show-toplevel)
+    rc=$?
+    [[ ${rc} -ne 0 ]] && return "${rc}"
+
+    [[ -z ${root} ]] && return 1
+    cd ${root}
+}
+
+[[ $? -ne 0 ]]
